### ISSUE TITLE
error: UART_0_NRF_UART, can't build

### ISSUE THREAD

**Issue by in06khattab** [foldedtoad/dwm1001#3]
I cannot build the first example.

Below is the log when I try to build. There is an error on UART_0_NRF_UART.
I tried adding the following to the prj.conf file, but it made no difference.
CONFIG_CONSOLE_SHELL=n
CONFIG_UART_CONSOLE=n
CONFIG_UART_0_NRF_UART=n
CONFIG_UART_0_NRF_UARTE=y

aa@aa-VirtualBox:~/zephyrproject/zephyr/dwm1001/examples/ex_01a_simple_tx$     cmake -B build -DBOARD=nrf52_dwm1001 .
-- Application: /home/aa/zephyrproject/zephyr/dwm1001/examples/ex_01a_simple_tx
-- Zephyr version: 2.3.99 (/home/aa/zephyrproject/zephyr)
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.2") found components: Interpreter 
-- Board: nrf52_dwm1001
ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found toolchain: zephyr (/home/aa/zephyr-sdk-0.11.3)
-- Found west: /home/aa/.local/bin/west (found suitable version "0.7.2", minimum required is "0.7.1")
-- Found dtc: /home/aa/zephyr-sdk-0.11.3/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found BOARD.dts: /home/aa/zephyrproject/zephyr/dwm1001/boards/arm/nrf52_dwm1001/nrf52_dwm1001.dts
-- Generated zephyr.dts: /home/aa/zephyrproject/zephyr/dwm1001/examples/ex_01a_simple_tx/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /home/aa/zephyrproject/zephyr/dwm1001/examples/ex_01a_simple_tx/build/zephyr/include/generated/devicetree_unfixed.h
Parsing /home/aa/zephyrproject/zephyr/Kconfig
Loaded configuration '/home/aa/zephyrproject/zephyr/dwm1001/boards/arm/nrf52_dwm1001/nrf52_dwm1001_defconfig'
Merged configuration '/home/aa/zephyrproject/zephyr/dwm1001/examples/ex_01a_simple_tx/prj.conf'

error: UART_0_NRF_UART (defined at drivers/serial/Kconfig.nrfx:25) is assigned in a configuration
file, but is not directly user-configurable (has no prompt). It gets its value indirectly from other
symbols. See http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_UART_0_NRF_UART.html
and/or look up UART_0_NRF_UART in the menuconfig/guiconfig interface. The Application Development
Primer, Setting Configuration Values, and Kconfig - Tips and Best Practices sections of the manual
might be helpful too.

CMake Error at /home/aa/zephyrproject/zephyr/cmake/kconfig.cmake:216 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  /home/aa/zephyrproject/zephyr/cmake/app/boilerplate.cmake:511 (include)
  CMakeLists.txt:6 (include)

-- Configuring incomplete, errors occurred!

**Comment by foldedtoad** [comment]
Hi in06khattab,
I believe this problem you're encountering is due to the Zephyr version.  The above build spew indicates that you have Zephyr V2.3.99 installed, but if you notice on the top-level README.md file the currently supported version is Zephyr V2.2.99.   I am currently working on migrating to V2.3.99, but haven't completed all the changes yet. The major changes have to due with DeviceTreeStructure (DTS) macros and interrupt handling. I believe you're hitting a DTS change to the UART definitions. When my upgrade happens, I will update the README.md file to indicate the newly supported Zephyr level.  Suggestion: can you fall back to Zephyr V2.2.99 and try it?

**Comment by yakinikuman** [comment]
I believe the Zephyr "x.y..99" version numbering scheme just means "some commits getting ready for x.y+1.0".  There might be several commits with VERSION should x.y.99.  There doesn't seem to be a tag for any .99 version.

That said, I was able to checkout zephyr 2.2.1 and example_01a built fine for me.

(PS - thanks for this repo!  I've been bashing my head for a few days trying to get RT-LOC's zephyr-dwm1001 working with a more updated zephyr baseline.  And that looks like exactly what you've done.  Thanks again; awesome job!)

**Comment by foldedtoad** [comment]
I have completed the upgrade to Zephyr V2.3.99.: see branch "zephyr_2.3.99".  By this I mean that all examples compile without errors.
I still need to go though all the examples a prove them against real hardware...this take time.
So, at this time I would consider this a reasonable "beta" release.
I will merge this beta branch into master when I finish hardware testing.
Of course, if you encounter problems, let me know.

**Comment by foldedtoad** [comment]
I have finished upgrading the code to meet Zephyr V2.3.xx levels.
